package com.phonefarm.client.model

/**
 * Device hardware capability assessment for local model inference.
 *
 * Generated by [ModelManager.checkDeviceCapability] on startup.
 * Used to determine:
 *   - Whether local inference is feasible (sufficient RAM + NPU/GPU)
 *   - Which model and quantization level is recommended
 *   - Which backend (CPU/Vulkan/NNAPI) will yield the best performance
 */
data class DeviceCapability(
    /** Whether the device can run a local VLM model at acceptable latency. */
    val supportsLocalModel: Boolean,

    /** Recommended model ID for this device (e.g., "autoglm-phone-9b-q4_k_m"). */
    val recommendedModel: String,

    /** The backend that will give the best inference performance. */
    val bestBackend: InferenceBackend,

    /** Total device RAM in megabytes. */
    val totalRamMb: Long,

    /** Currently available RAM in megabytes. */
    val availableRamMb: Long,

    /** Free internal storage in megabytes. */
    val freeStorageMb: Long,

    /** GPU model name (e.g., "Adreno (TM) 750", "Mali-G710"). */
    val gpuModel: String,

    /** Whether a Neural Processing Unit is available. */
    val npuAvailable: Boolean,

    /** Whether the Vulkan compute API is available. */
    val vulkanAvailable: Boolean,

    /** Whether Android Neural Networks API (NNAPI) is available. */
    val nnapiAvailable: Boolean,

    /** Capability warnings (e.g., low RAM, outdated GPU, missing NPU driver). */
    val warnings: List<String>,
)

/**
 * Available inference backends for on-device model execution.
 *
 * Ordered from fastest (QCOM_QNN) to slowest (CPU_ONLY).
 */
enum class InferenceBackend {
    /** CPU-only inference via llama.cpp (works everywhere, slowest). */
    CPU_ONLY,

    /** Vulkan compute shaders for GPU acceleration. */
    VULKAN,

    /** Android Neural Networks API (NNAPI) — uses available accelerators. */
    NNAPI,

    /** Qualcomm QNN delegate for Snapdragon NPU. */
    QCOM_QNN,

    /** MediaTek NeuroPilot for Dimensity APU. */
    MTK_NEUROPILOT,

    /** Huawei HiAI for Kirin NPU. */
    HUAWEI_HIAI,
}
