/**
 * Script Compiler — Compiles VLM episodes into reusable automation scripts.
 *
 * Supports dual-target code generation:
 *   - targetRuntime="deeke" → DeekeScript API (UiSelector(), Gesture.click(), etc.)
 *   - targetRuntime="autox" → AutoX v7 API (selector(), click(), etc.)
 *
 * Compilation process:
 *   1. Extract action sequence from episode steps
 *   2. For each coordinate-based action, map to UI node selectors via node-inspector
 *   3. Score selector stability: id > text+className > desc > className > coordinate fallback
 *   4. Generate runtime-compatible source code
 */
import type { StepResult } from './vlm-orchestrator';

export interface CompiledScript {
  name: string;
  platform: string;
  targetRuntime: 'deeke' | 'autox';
  sourceCode: string;
  selectorCount: number;
  totalSteps: number;
}

export interface CompileOptions {
  /** Target runtime for code generation (default: 'deeke') */
  targetRuntime?: 'deeke' | 'autox';
}

/**
 * Compile a VLM episode into an automation script.
 * @param steps - The recorded steps from a VLM episode
 * @param name - Script name
 * @param platform - Target platform (dy/ks/wx/xhs)
 * @param nodeSelectors - Optional pre-resolved UI selectors per step (from inspect-at-coord)
 * @param options - Compilation options (targetRuntime, etc.)
 */
export function compileEpisode(
  steps: StepResult[],
  name: string,
  platform: string,
  nodeSelectors?: Map<number, NodeSelector>,
  options?: CompileOptions,
): CompiledScript {
  const targetRuntime = options?.targetRuntime || 'deeke';
  const isAutoX = targetRuntime === 'autox';
  const lines: string[] = [];
  let selectorCount = 0;

  const runtimeBanner = isAutoX
    ? 'AutoX v7 (Rhino mode) — compiled by VLM Script Compiler'
    : 'DeekeScript — compiled by VLM Script Compiler';

  lines.push('/**');
  lines.push(` * Auto-generated by VLM Script Compiler`);
  lines.push(` * Target: ${runtimeBanner}`);
  lines.push(` * Platform: ${platform}`);
  lines.push(` * Steps: ${steps.length}`);
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(' */');
  lines.push('');

  if (isAutoX) {
    lines.push('// AutoX v7 native API — no compat layer needed');
    lines.push('var AppAutomation = global.AppAutomation;');
    lines.push('var remoteBridge = global.remoteBridge;');
  } else {
    lines.push('var AppAutomation = global.AppAutomation;');
    lines.push('var remoteBridge = global.remoteBridge;');
  }
  lines.push('');
  lines.push(`// Task: ${name}`);
  lines.push('function main() {');

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];
    const selector = nodeSelectors?.get(i);

    lines.push(`  // Step ${i}: ${step.action.type}`);
    if (step.thinking) {
      lines.push(`  // Reasoning: ${step.thinking.slice(0, 80).replace(/\n/g, ' ')}`);
    }

    if (selector) {
      selectorCount++;
      lines.push(`  ${generateSelectorLine(selector, isAutoX)}`);
    } else {
      lines.push(`  ${generateCoordinateLine(step, isAutoX)}`);
    }
    lines.push(`  sleep(500);`);
    lines.push('');
  }

  lines.push('  remoteBridge.sendTaskResult("completed", { steps: ' + steps.length + ' });');
  lines.push('}');
  lines.push('');
  lines.push('main();');

  return {
    name,
    platform,
    targetRuntime,
    sourceCode: lines.join('\n'),
    selectorCount,
    totalSteps: steps.length,
  };
}

export interface NodeSelector {
  type: 'id' | 'text' | 'desc' | 'textContains' | 'descContains' | 'className' | 'coordinate';
  value: string;
  className?: string;
  x?: number;
  y?: number;
  stability: number; // 0-100
}

function generateSelectorLine(sel: NodeSelector, isAutoX?: boolean): string {
  if (isAutoX) return generateAutoXSelectorLine(sel);
  switch (sel.type) {
    case 'id':
      return `AppAutomation.clickById('${sel.value}');`;
    case 'text':
      return `AppAutomation.clickByText('${sel.value}');`;
    case 'desc':
      return `AppAutomation.clickByDesc('${sel.value}');`;
    case 'textContains':
      return `AppAutomation.safeClick(function() { return UiSelector().textContains('${sel.value}').clickable(true); });`;
    case 'descContains':
      return `AppAutomation.safeClick(function() { return UiSelector().descContains('${sel.value}').clickable(true); });`;
    case 'className':
      return `AppAutomation.safeClick(function() { return UiSelector().className('${sel.value}').clickable(true); });`;
    case 'coordinate':
      return `AppAutomation.clickXY(${sel.x}, ${sel.y});`;
    default:
      return `// Unknown selector type: ${sel.type}`;
  }
}

function generateAutoXSelectorLine(sel: NodeSelector): string {
  switch (sel.type) {
    case 'id':
      return `AppAutomation.clickById('${sel.value}');`;
    case 'text':
      return `AppAutomation.clickByText('${sel.value}');`;
    case 'desc':
      return `AppAutomation.clickByDesc('${sel.value}');`;
    case 'textContains':
      return `AppAutomation.safeClick(function() { return selector().textContains('${sel.value}').clickable(true); });`;
    case 'descContains':
      return `AppAutomation.safeClick(function() { return selector().descContains('${sel.value}').clickable(true); });`;
    case 'className':
      return `AppAutomation.safeClick(function() { return selector().className('${sel.value}').clickable(true); });`;
    case 'coordinate':
      return `AppAutomation.clickXY(${sel.x}, ${sel.y});`;
    default:
      return `// Unknown selector type: ${sel.type}`;
  }
}

function generateCoordinateLine(step: StepResult, isAutoX?: boolean): string {
  const a = step.action;
  if (isAutoX) return generateAutoXCoordinateLine(step);
  switch (a.type) {
    case 'tap':
      return `Gesture.click(${a.x}, ${a.y});`;
    case 'swipe':
      return `Gesture.swipe(${a.x}, ${a.y}, ${a.x2}, ${a.y2}, 400);`;
    case 'type':
      return `KeyBoards.inputText('${(a.text || '').replace(/'/g, "\\'")}');`;
    case 'back':
      return 'Common.back();';
    case 'home':
      return 'Common.home();';
    case 'launch':
      return `App.launch('${a.package}');`;
    default:
      return `// Unknown action: ${a.type}`;
  }
}

function generateAutoXCoordinateLine(step: StepResult): string {
  const a = step.action;
  switch (a.type) {
    case 'tap':
      return `click(${a.x}, ${a.y});`;
    case 'swipe':
      return `swipe(${a.x}, ${a.y}, ${a.x2}, ${a.y2}, 400);`;
    case 'type':
      return `inputText('${(a.text || '').replace(/'/g, "\\'")}');`;
    case 'back':
      return 'back();';
    case 'home':
      return 'home();';
    case 'launch':
      return `app.launch('${a.package}');`;
    default:
      return `// Unknown action: ${a.type}`;
  }
}

/**
 * Calculate selector stability score based on selector type.
 * id = 100, text+className = 80, text alone = 70, desc = 60, className = 30, coordinate = 0
 */
export function scoreSelectorStability(sel: NodeSelector): number {
  const baseScores: Record<string, number> = {
    id: 100, text: 70, desc: 60, textContains: 65, descContains: 55,
    className: 30, coordinate: 0,
  };
  let score = baseScores[sel.type] || 10;
  if (sel.className) score += 15; // Bonus for combined className
  return Math.min(100, score);
}
