package com.phonefarm.client.floating

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Paint
import androidx.core.content.FileProvider
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import java.io.FileOutputStream
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Helper for sharing VLM task results from the float window.
 *
 * After a VLM task completes, the user can share the result as:
 *   - A text summary (ACTION_SEND intent with task timeline)
 *   - An image card (rendered summary bitmap attached to intent)
 *   - A script file (.js AutoX script attached as file)
 *
 * Supported share targets:
 *   - WeChat, QQ, messaging apps (text + image)
 *   - DeekeScript / AutoX app (script file import)
 *   - PhoneFarm control server (direct upload)
 */
@Singleton
class FloatShareHelper @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    /**
     * Share a text summary of the task result.
     *
     * @param taskName     The original task description.
     * @param totalSteps   Number of steps executed.
     * @param durationMs   Execution duration in milliseconds.
     * @param success      Whether the task completed successfully.
     */
    fun shareTextSummary(
        taskName: String,
        totalSteps: Int,
        durationMs: Long,
        success: Boolean,
    ) {
        val status = if (success) "Success" else "Failed"
        val durationFormatted = formatDuration(durationMs)
        val text = buildString {
            appendLine("PhoneFarm Task Result")
            appendLine("Task: $taskName")
            appendLine("Status: $status")
            appendLine("Steps: $totalSteps")
            appendLine("Duration: $durationFormatted")
            appendLine("Generated by PhoneFarm VLM Agent")
        }

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
            putExtra(Intent.EXTRA_SUBJECT, "PhoneFarm: $taskName")
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
        val chooser = Intent.createChooser(intent, "Share task result")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }

    /**
     * Share the result as a rendered summary card image.
     *
     * @param summaryBitmap A pre-rendered Bitmap of the task summary card.
     */
    fun shareAsImage(summaryBitmap: Bitmap) {
        val cacheDir = File(context.cacheDir, "share")
        cacheDir.mkdirs()
        val imageFile = File(cacheDir, "phonefarm_task_${System.currentTimeMillis()}.png")

        try {
            FileOutputStream(imageFile).use { fos ->
                summaryBitmap.compress(Bitmap.CompressFormat.PNG, 100, fos)
            }

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                imageFile,
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "image/png"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_TEXT, "PhoneFarm task result")
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            val chooser = Intent.createChooser(intent, "Share as image")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            android.util.Log.e("FloatShareHelper", "Failed to share image", e)
        }
    }

    /**
     * Share the compiled script .js file for import into DeekeScript.
     *
     * @param jsContent  The compiled JavaScript source code.
     * @param scriptName The human-readable script name.
     */
    fun shareScriptFile(jsContent: String, scriptName: String) {
        val cacheDir = File(context.cacheDir, "share")
        cacheDir.mkdirs()
        val safeName = scriptName.replace(Regex("[^a-zA-Z0-9_\\-\\u4e00-\\u9fff]"), "_")
        val scriptFile = File(cacheDir, "$safeName.js")

        try {
            scriptFile.writeText(jsContent, Charsets.UTF_8)

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                scriptFile,
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/javascript"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_TEXT, "PhoneFarm script: $scriptName")
                putExtra(Intent.EXTRA_SUBJECT, scriptName)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            // Try targeting DeekeScript package if installed
            try {
                intent.setPackage("com.deekescript.app")
            } catch (_: Exception) {
                // Package not installed 鈥?use chooser
            }

            val chooser = Intent.createChooser(intent, "Share script: $scriptName")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            android.util.Log.e("FloatShareHelper", "Failed to share script file", e)
        }
    }

    /**
     * Render a simple summary card bitmap for sharing as an image.
     *
     * This is a convenience method that creates a text-based card showing
     * the task summary. For production use, a proper Compose-rendered card
     * would be more polished.
     */
    fun renderSummaryCard(
        taskName: String,
        totalSteps: Int,
        durationMs: Long,
        success: Boolean,
    ): Bitmap {
        val width = 800
        val height = 400
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)

        // Background
        val bgPaint = Paint().apply {
            color = if (success) 0xFFF0FFF0.toInt() else 0xFFFFF0F0.toInt()
            style = Paint.Style.FILL
        }
        canvas.drawRect(0f, 0f, width.toFloat(), height.toFloat(), bgPaint)

        // Title
        val titlePaint = Paint().apply {
            color = 0xFF333333.toInt()
            textSize = 36f
            isAntiAlias = true
            isFakeBoldText = true
        }
        canvas.drawText("PhoneFarm Task", 40f, 60f, titlePaint)

        // Status
        val statusPaint = Paint().apply {
            color = if (success) 0xFF2E7D32.toInt() else 0xFFC62828.toInt()
            textSize = 28f
            isAntiAlias = true
        }
        val status = if (success) "SUCCESS" else "FAILED"
        canvas.drawText("Status: $status", 40f, 120f, statusPaint)

        // Details
        val detailPaint = Paint().apply {
            color = 0xFF666666.toInt()
            textSize = 22f
            isAntiAlias = true
        }
        canvas.drawText("Task: ${taskName.take(60)}", 40f, 180f, detailPaint)
        canvas.drawText("Steps: $totalSteps", 40f, 220f, detailPaint)
        canvas.drawText("Duration: ${formatDuration(durationMs)}", 40f, 260f, detailPaint)
        canvas.drawText("Generated by PhoneFarm VLM Agent", 40f, 340f, detailPaint)

        return bitmap
    }

    private fun formatDuration(ms: Long): String = when {
        ms < 1000 -> "${ms}ms"
        ms < 60_000 -> "${ms / 1000}s"
        else -> {
            val minutes = ms / 60_000
            val seconds = (ms % 60_000) / 1000
            "${minutes}m ${seconds}s"
        }
    }
}
