package com.phonefarm.client.vlm

import android.view.accessibility.AccessibilityNodeInfo
import com.phonefarm.client.data.local.dao.EpisodeDao
import com.phonefarm.client.data.local.dao.SavedScriptDao
import com.phonefarm.client.data.local.dao.VlmStepDao
import com.phonefarm.client.data.local.entity.EpisodeEntity
import com.phonefarm.client.data.local.entity.SavedScriptEntity
import com.phonefarm.client.data.local.entity.VlmStepEntity
import com.phonefarm.client.service.PhoneFarmAccessibilityService
import org.json.JSONObject
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Compile a recorded VLM episode into a reusable AutoX v7 .js script.
 *
 * The compilation pipeline:
 *   1. Load saved episode steps
 *   2. For each step with a coordinate-based action, inspect the UI node
 *      at that coordinate to derive a stable selector (id > text > desc > class > xpath)
 *   3. Assign a stability score to each selector
 *   4. Generate DeekeScript-compatible JavaScript source code
 *   5. Optionally validate the script by executing it in dry-run mode
 */
@Singleton
class ScriptCompiler @Inject constructor(
    private val episodeDao: EpisodeDao,
    private val vlmStepDao: VlmStepDao,
    private val savedScriptDao: SavedScriptDao,
) {

    /** Reference to the accessibility service (nullable — may not be running). */
    private val accessibilityService: PhoneFarmAccessibilityService?
        get() = PhoneFarmAccessibilityService.instance

    /**
     * Compile an episode into a reusable .js script.
     *
     * @param episodeId  The recorded episode to compile.
     * @param scriptName Human-readable name for the generated script.
     * @param platform   Target platform (douyin, kuaishou, wechat, xiaohongshu, etc.).
     * @return The generated JavaScript source code as a String.
     */
    suspend fun compile(
        episodeId: String,
        scriptName: String,
        platform: String,
    ): String {
        val episode = episodeDao.get(episodeId)
            ?: throw IllegalArgumentException("Episode not found: $episodeId")

        val steps = vlmStepDao.getByEpisode(episodeId)
        if (steps.isEmpty()) throw IllegalArgumentException("Episode has no recorded steps")

        val jsCode = buildString {
            appendLine("// Auto-generated by PhoneFarm ScriptCompiler")
            appendLine("// Episode: ${episode.taskPrompt}")
            appendLine("// Source: $episodeId | Model: ${episode.modelName}")
            appendLine("// Platform: $platform | Steps: ${steps.size}")
            appendLine("// Generated at: ${System.currentTimeMillis()}")
            appendLine()
            appendLine("auto.waitFor();")
            appendLine("console.log('Starting script: $scriptName');")
            appendLine()

            for (step in steps) {
                val action = parseActionFromJson(step.actionJson)
                if (action != null) {
                    appendLine(generateJsForAction(step, action))
                }
            }

            appendLine()
            appendLine("console.log('Script completed: $scriptName');")
        }

        // Save compiled script to DB
        val scriptId = UUID.randomUUID().toString()
        val now = System.currentTimeMillis()
        savedScriptDao.upsert(
            SavedScriptEntity(
                scriptId = scriptId,
                name = scriptName,
                platform = platform,
                category = "vlm_compiled",
                episodeId = episodeId,
                jsContent = jsCode,
                jsFilePath = null,
                syncedToCloud = false,
                isQuickChip = false,
                createdAt = now,
                updatedAt = now,
            )
        )

        return jsCode
    }

    /**
     * Inspect the UI node at the given pixel coordinate and generate a
     * SelectorInfo with the most stable selector available.
     */
    fun inspectAtCoordinate(
        x: Int,
        y: Int,
        rootNode: AccessibilityNodeInfo?,
    ): SelectorInfo {
        if (rootNode == null) {
            return SelectorInfo(
                selector = "click($x, $y)",
                stabilityScore = 10,
                selectorType = "coordinate_fallback",
            )
        }

        val node = findNodeAtCoordinate(rootNode, x, y)
        if (node == null) {
            return SelectorInfo(
                selector = "click($x, $y)",
                stabilityScore = 10,
                selectorType = "coordinate_fallback",
            )
        }

        return try {
            // Priority selection: id > text+className > desc > className > xpath
            val selectors = mutableListOf<Triple<String, String, Int>>()

            // 1. Resource ID (most stable) → score 95
            val resId = node.viewIdResourceName
            if (!resId.isNullOrBlank()) {
                val shortId = resId.substringAfterLast('/')
                if (shortId.isNotBlank() && shortId != "NoId") {
                    selectors.add(Triple("id(\"$shortId\")", "id", 95))
                }
            }

            // 2. Text + className → score 85
            val text = node.text?.toString()
            val className = node.className?.toString()
            if (!text.isNullOrBlank() && !className.isNullOrBlank()) {
                selectors.add(
                    Triple(
                        "text(\"$text\").className(\"$className\")",
                        "text_class",
                        85,
                    )
                )
            }

            // 3. Text only → score 80
            if (!text.isNullOrBlank()) {
                selectors.add(Triple("text(\"$text\")", "text", 80))
            }

            // 4. Content description → score 70
            val desc = node.contentDescription?.toString()
            if (!desc.isNullOrBlank()) {
                selectors.add(Triple("desc(\"$desc\")", "desc", 70))
            }

            // 5. Class name → score 50
            if (!className.isNullOrBlank()) {
                selectors.add(Triple("className(\"$className\")", "class", 50))
            }

            // 6. XPath (least stable) → score 20
            val xpath = buildXPath(node)
            if (xpath != null) {
                selectors.add(Triple(xpath, "xpath", 20))
            }

            val best = selectors.maxByOrNull { it.third }
                ?: Triple("click($x, $y)", "coordinate_fallback", 10)

            SelectorInfo(
                selector = best.first,
                stabilityScore = best.third,
                selectorType = best.second,
            )
        } finally {
            node.recycle()
        }
    }

    // ======== Data class ========

    data class SelectorInfo(
        val selector: String,
        val stabilityScore: Int,
        val selectorType: String, // "id", "text_class", "desc", "class", "xpath", "coordinate_fallback"
    )

    // ======== Private helpers ========

    /**
     * Parse a JSON action string back to a VLMAction for code generation.
     */
    private fun parseActionFromJson(actionJson: String?): VLMAction? {
        if (actionJson.isNullOrBlank()) return null
        return try {
            val json = JSONObject(actionJson)
            val actionName = json.optString("action", "").lowercase()
            when (actionName) {
                "tap" -> VLMAction.Tap(
                    json.getInt("x"), json.getInt("y")
                )
                "long_press" -> VLMAction.LongPress(
                    json.getInt("x"), json.getInt("y"),
                    json.optLong("duration_ms", 800),
                )
                "swipe" -> VLMAction.Swipe(
                    json.getInt("x1"), json.getInt("y1"),
                    json.getInt("x2"), json.getInt("y2"),
                    json.optLong("duration_ms", 300),
                )
                "type" -> VLMAction.Type(json.getString("text"))
                "back" -> VLMAction.Back
                "home" -> VLMAction.Home
                "launch" -> VLMAction.Launch(json.getString("package"))
                "terminate" -> VLMAction.Terminate(
                    json.optString("message", "")
                )
                else -> null
            }
        } catch (_: Exception) {
            null
        }
    }

    /**
     * Generate JS code for a single action step.
     * Uses AutoX v7 / DeekeScript compatible APIs.
     */
    private fun generateJsForAction(
        step: VlmStepEntity,
        action: VLMAction,
    ): String {
        val lines = mutableListOf<String>()

        // Add thinking as a comment
        if (!step.modelThinking.isNullOrBlank()) {
            lines.add("// Step ${step.stepNumber}: ${step.modelThinking.take(80)}")
        }

        when (action) {
            is VLMAction.Tap -> {
                // Try to generate selector-based click; fall back to coordinates
                val selector = step.selectorInfoJson?.let { extractSelector(it) }
                if (selector != null && selector.stabilityScore >= 70) {
                    lines.add("${selector.selector}.findOne(3000)?.click();")
                } else {
                    lines.add("click(${action.x}, ${action.y});")
                }
                lines.add("sleep(1000);")
            }
            is VLMAction.LongPress -> {
                lines.add("longClick(${action.x}, ${action.y});")
                lines.add("sleep(${action.durationMs});")
            }
            is VLMAction.Swipe -> {
                lines.add(
                    "swipe(${action.x1}, ${action.y1}, ${action.x2}, ${action.y2}, ${action.durationMs});"
                )
                lines.add("sleep(500);")
            }
            is VLMAction.Type -> {
                lines.add("setText(\"${action.text.replace("\"", "\\\"")}\");")
                lines.add("sleep(500);")
            }
            is VLMAction.Back -> {
                lines.add("back();")
                lines.add("sleep(500);")
            }
            is VLMAction.Home -> {
                lines.add("home();")
                lines.add("sleep(500);")
            }
            is VLMAction.Launch -> {
                lines.add("launch(\"${action.packageName}\");")
                lines.add("sleep(3000);")
            }
            is VLMAction.Terminate -> {
                lines.add("// Task complete: ${action.message}")
                lines.add("console.log('Task finished: ${action.message.replace("\"", "\\\"")}');")
            }
        }

        return lines.joinToString("\n")
    }

    private fun extractSelector(selectorInfoJson: String): SelectorInfo? {
        return try {
            val json = JSONObject(selectorInfoJson)
            SelectorInfo(
                selector = json.getString("selector"),
                stabilityScore = json.getInt("stabilityScore"),
                selectorType = json.getString("selectorType"),
            )
        } catch (_: Exception) {
            null
        }
    }

    /**
     * Find the deepest accessibility node at the given screen coordinates.
     */
    private fun findNodeAtCoordinate(
        root: AccessibilityNodeInfo,
        x: Int,
        y: Int,
    ): AccessibilityNodeInfo? {
        // Use AccessibilityNodeInfo's built-in hit test (API 33+) or manual bounds check
        val rect = android.graphics.Rect()
        val candidates = mutableListOf<AccessibilityNodeInfo>()

        collectNodesInBounds(root, x, y, candidates)

        // Return the deepest (smallest area) node that contains the point
        return candidates.minByOrNull {
            val r = android.graphics.Rect()
            it.getBoundsInScreen(r)
            r.width() * r.height()
        }
    }

    private fun collectNodesInBounds(
        node: AccessibilityNodeInfo,
        x: Int,
        y: Int,
        results: MutableList<AccessibilityNodeInfo>,
    ) {
        val rect = android.graphics.Rect()
        node.getBoundsInScreen(rect)

        if (rect.contains(x, y)) {
            results.add(AccessibilityNodeInfo.obtain(node))
        }

        for (i in 0 until node.childCount) {
            val child = node.getChild(i) ?: continue
            collectNodesInBounds(child, x, y, results)
            child.recycle()
        }
    }

    /**
     * Build an XPath-like selector for a node.
     * Simplified: className[index] path from root.
     */
    private fun buildXPath(node: AccessibilityNodeInfo): String? {
        val parts = mutableListOf<String>()
        var current: AccessibilityNodeInfo? = AccessibilityNodeInfo.obtain(node)

        while (current != null) {
            val cn = current.className?.toString() ?: break
            val parent = current.parent
            if (parent != null) {
                // Find index among siblings of same class
                var index = 0
                var siblingIndex = 0
                for (i in 0 until parent.childCount) {
                    val sibling = parent.getChild(i) ?: continue
                    if (sibling.className?.toString() == cn) {
                        if (sibling.equals(current)) {
                            index = siblingIndex
                        }
                        siblingIndex++
                    }
                    sibling.recycle()
                }
                parts.add(0, "$cn[$index]")
                parent.recycle()
            }
            if (current != node) current.recycle()
            current = parent
        }

        return if (parts.isNotEmpty()) parts.joinToString("/") else null
    }
}
